spring.application.name=HotelHub

#DB configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/HotelHub
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.servlet.context-path=/api/v1

jwt.secretKey=a8sd6faihdfjkas2398789afhdskjasdfh87yhk3jha987sdf89aabsdf876

#give the frontend url..now we dont have that so i have given the backend url
frontend.url=http://localhost:8080

